project/blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .import views
from .views import MyLogoutView


urlpatterns = [
    path('', views.index, name="index"),
    path("post/<str:name>/<int:id>/", views.post, name="post"),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contacts', views.contact, name='contacts'),
    path('category/<str:c>', views.category, name='category'),
    path('search', views.search, name='search'),
    path('create', views.create, name='create'),
    path('login', LoginView.as_view(), name='blog_login'),
    # path('login', LoginView.as_view(), name='blog_login'),
    path('logout', MyLogoutView.as_view(), name='blog_logout'),
    # path('login', MyLoginView.as_view(), name='blog_login'),
    path('profile/', views.profile, name='profile'),
    path('registration', views.registration, name='registration'),
    path('registration_success', views.registration_success, name='registration_success'),
    path('update_profile', views.update_profile, name='update_profile')

]

project/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

project/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

project/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

project/templates/shop/base.html
<!doctype html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <!-- Custom CSS -->
    <link href="{% static 'shop/style.css' %}" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-dark bg-dark fixed-top">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacts' %}">Contact</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Category
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
               {% for category in categories %}
                <li>
                    <a class="dropdown-item" href="{% url 'shop:product_list_by_category' category.slug %}">{{category.name}}</a>
                </li>
                {% endfor %}
            </ul>
          </li>
        </ul>
      </div>
    </div>

      <form class="d-flex mt-3" role="search">
           <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
           <button class="btn btn-success" type="submit">Search</button>
      </form>
        <div>
            {% include 'blog/toggle_login.html' %}
        </div>
            <div class="cart-in-header position-relative">
                <span class="position-absolute top-10 start-100 translate-middle badge rounded-pill bg-danger">
                    {{ cart|length }}</span>
                <a href="{% url 'cart:cart_detail' %}">${{ cart.get_total_price }}<img class="cart-icon" src="{% static 'img/cart.png' %}"></a>
            </div>

  </div>
</nav>


<!--    <div class="sticky-top">-->
<!--<div class="container">-->
<!--    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">-->
<!--&lt;!&ndash;        <nav class="navbar navbar-dark bg-dark fixed-top">&ndash;&gt;-->
<!--            <div class="container-fluid">-->
<!--                <a class="navbar-brand" href="#"></a>-->
<!--                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">-->
<!--                    <span class="navbar-toggler-icon"></span>-->
<!--                </button>-->
<!--                <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">-->
<!--                    <div class="offcanvas-header">-->
<!--                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Dark offcanvas</h5>-->
<!--                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>-->
<!--                    </div>-->
<!--                    <div class="offcanvas-body">-->
<!--                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">-->
<!--                            <li class="nav-item">-->
<!--                                <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item">-->
<!--                                <a class="nav-link" href="{% url 'contacts' %}">Contact</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item">-->
<!--                                <a class="nav-link" href="{% url 'contacts' %}">Services</a>-->
<!--                            </li>-->
<!--                            <li class="nav-item dropdown">-->
<!--                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--                                Category-->
<!--                                </a>-->
<!--                                <ul class="dropdown-menu dropdown-menu-dark">-->
<!--                                    {% for category in categories %}-->
<!--                                    <li>-->
<!--                                        <a class="dropdown-item" href="{% url 'shop:product_list_by_category' category.slug %}">{{category.name}}</a>-->
<!--                                    </li>-->
<!--                                    {% endfor %}-->
<!--                                </ul>-->
<!--                            </li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </nav>-->


<!--        <form class="d-flex mt-3" role="search">-->
<!--           <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--           <button class="btn btn-success" type="submit">Search</button>-->
<!--        </form>-->
<!--        <div>-->
<!--            {% include 'blog/toggle_login.html' %}-->
<!--        </div>-->
<!--            <div class="cart-in-header position-relative">-->
<!--                <span class="position-absolute top-10 start-100 translate-middle badge rounded-pill bg-danger">-->
<!--                    {{ cart|length }}</span>-->
<!--                <a href="{% url 'cart:cart_detail' %}">${{ cart.get_total_price }}<img class="cart-icon" src="{% static 'img/cart.png' %}"></a>-->
<!--            </div>-->
<!--    </div>-->

<!--<div id="header">-->
<!--    <a href="{% url 'shop:product_list' %}" class="logo">My shop</a>-->
<!--</div>-->
<!--<div id="subheader">-->
<!--    <div class="cart">-->
<!--        {% with total_items=cart|length %}-->
<!--        {% if cart|length > 0 %}-->
<!--        Your cart:-->
<!--        <a href="{% url 'cart:cart_detail' %}">{{total_items}}item{{total_items|pluralize}},-->
<!--        ${{cart.get_total_price}}</a>-->
<!--        {% else %}-->
<!--        Your cart is empty.-->
<!--        {% endif %}-->
<!--        {% endwith %}-->

<!--    </div>-->
<!--</div>-->

<!--            {% if user.is_authenticated %}-->

<!--            {% endif %}-->
<!--             <li>-->
<!--                <a href="{% url 'shop:product_list' %}">Shop</a>-->
<!--            </li>-->

<div class="content">
    {% block content %}
    {% endblock %}
</div>
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Blog 2024</p>
            </div>
                <!-- /.col-lg-12 -->
        </div>
            <!-- /.row -->
    </footer>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>