project/blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .import views
from .views import MyLogoutView


urlpatterns = [
    path('', views.index, name="index"),
    path("post/<str:name>/<int:id>/", views.post, name="post"),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contacts', views.contact, name='contacts'),
    path('category/<str:c>', views.category, name='category'),
    path('search', views.search, name='search'),
    path('create', views.create, name='create'),
    path('login', LoginView.as_view(), name='blog_login'),
    # path('login', LoginView.as_view(), name='blog_login'),
    path('logout', MyLogoutView.as_view(), name='blog_logout'),
    # path('login', MyLoginView.as_view(), name='blog_login'),
    path('profile/', views.profile, name='profile'),
    path('registration', views.registration, name='registration'),
    path('registration_success', views.registration_success, name='registration_success'),
    path('update_profile', views.update_profile, name='update_profile')

]

project/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

project/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

project/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

project/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="container row-block">
        <span class="container"><h1>{{ product.name }}</h1></span>
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">

        <h6><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h6>
        <p class="price"><h4>${{ product.price }}</h4></p>
        {{ product.description|linebreaks }}
        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
            {% csrf_token %}
            {{cart_product_form}}
            <input type="submit" value="Add to cart">
        </form>
    </div>
{% endblock %}

project/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<!--    <div class="container">-->
<!--        <h3>Categories</h3>-->
<!--        <ul>-->
<!--            <li {% if not category %} class="selected" {% endif %}>-->
<!--                <a href="{% url 'shop:product_list' %}">All</a>-->
<!--            </li>-->
<!--            {% for c in categories %}-->
<!--                <li {% if category.slug == c.slug %}class="selected"{% endif %}>-->
<!--                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>-->
<!--                </li>-->
<!--            {% endfor %}-->
<!--        </ul>-->
<!--    </div>-->

        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        <div class="container">
            {% for product in products %}
            <div class="row-block row">
                <div class="col-md-8">
                    <a href="{{ product.get_absolute_url }}">
                        <img class="img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                    </a>
                </div>
                <div class="col-md-4 d-flex align-items-center justify-content-center">
                    <div>
                    <a href="{{ product.get_absolute_url }}"><h6>{{ product.name }}</h6></a>
                        <span class="font">{{ product.description }}</span>
                    </div>
                </div>
                <span class="fs-3 price-block">${{ product.price }}</span>
            </div>
          {% endfor %}
        </div>


{% endblock %}