project/blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .import views
from .views import MyLogoutView


urlpatterns = [
    path('', views.index, name="index"),
    path("post/<str:name>/<int:id>/", views.post, name="post"),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contacts', views.contact, name='contacts'),
    path('category/<str:c>', views.category, name='category'),
    path('search', views.search, name='search'),
    path('create', views.create, name='create'),
    path('login', LoginView.as_view(), name='blog_login'),
    # path('login', LoginView.as_view(), name='blog_login'),
    path('logout', MyLogoutView.as_view(), name='blog_logout'),
    # path('login', MyLoginView.as_view(), name='blog_login'),
    path('profile/', views.profile, name='profile'),
    path('registration', views.registration, name='registration'),
    path('registration_success', views.registration_success, name='registration_success'),
    path('update_profile', views.update_profile, name='update_profile')

]

project/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove')
]

project/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create')
]

project/project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('gallery/', include('gallery.urls')),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('shop', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.product_detail, name='product_detail')
]

project/cart/models.py
from django.db import models

# Create your models here.

project/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 20)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

project/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
   Cart
{% endblock %}
{% block content %}
<h1>Your shopping cart</h1>
<table class="cart">
    <thead>
    <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
    <tr>
        <td>
            <a href="{{ product.get_absolute_url }}">
                <img src="
                            {% if product.image %}
                                {{ product.image.url }}
                            {% else %}
                                {% static 'img/no_img.png' %}
                            {% endif %}">
            </a>
        </td>
<td>{{product.name}}</td>
<td>{{item.quantity}}</td>
<td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
<td class="num">${{item.price}}</td>
<td class="num">${{item.total_price}}</td>
</tr>
{% endwith %}
{% endfor %}
<tr class="total">
    <td>Total</td>
    <td colspan="4"></td>
    <td class="num">${{ cart.get_total_price }}</td>
</tr>
</tbody>
</table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
</p>
{% endblock %}